### ISSUE TITLE
anomalie build site : resource not found in file cache

### ISSUE THREAD

**Issue by strainel** [spyrales/web#1]
le build ne passe pas ; cf. [rapport travis-ci](https://travis-ci.org/github/spyrales/web/builds/664562250)

`Error: Error building site: TOCSS: failed to transform "scss/style.scss" (text/x-scss): resource "scss/web/scss/style.scss_b95b077eb505d5c0aff8055eaced30ad" not found in file cache`

Le problème semble venir de la dernière version de Hugo publié il y a quelques jours.
https://github.com/gohugoio/hugoThemes/issues/822

**Comment by RLesur** [comment]
Ne faudrait-il pas figer la version d'Hugo utilisée et ne pas prendre la dernière ?

**Comment by RLesur** [comment]
Je pense avoir réparé le CI : 

- https://github.com/spyrales/web/commit/70a980b6c45208eca8db03780acfad9fb0475a71 fige la version de Hugo à 0.67.0
- https://github.com/spyrales/web/commit/1d19371bd1df54e3de8cecf1eeae196862a2e05e utilise Hugo extended, indispensable, car le thème choisi utilise SASS/SCSS

**Comment by strainel** [comment]
top ! j'y ai perdu mon latin hier soir...
