### ISSUE TITLE
Erreur 404 pour plugins/bootstrap/bootstrap.min.css

### ISSUE THREAD

**Issue by RLesur** [spyrales/web#10]
Même contexte que #9 : je vais sur la page de contact et je retourne en arrière.

Je me retrouve avec un 404 pour la ressource https://spyrales.github.io/web/plugins/bootstrap/bootstrap.min.css

![](https://user-images.githubusercontent.com/19177171/77207365-79bc3580-6af9-11ea-8d25-f1f41b86d355.png)

**Comment by strainel** [comment]
j'ai ouvert une PR également sur le master du thème... 
https://github.com/themefisher/airspace-hugo/pull/68

**Comment by strainel** [comment]
closed by #18
