### ISSUE TITLE
lien brisé sur un article du blog

### ISSUE THREAD

**Issue by strainel** [spyrales/web#108]
bonjour @linogaliana 

Le lien en bas de [cet article](https://www.spyrales.fr/blog/20200418-introduction-datatable/) est brisé. Peux tu indiquer le nouveau lien ?

Lien brisé : https://www.spyrales.fr/blog/20200418-introduction-datatable/

merci

**Comment by linogaliana** [comment]
Le *post* a disparu de mon site suite aux dernières modifications. Je n'avais pas vu, merci de me l'avoir signalé. Je vais régénérer le site et remettre au même lien le post, je te signale quand ce sera réglé

**Comment by linogaliana** [comment]
L'article a été à nouveau intégré au site web. L'url est le même qu'avant, il n'y a donc pas à changer le post sur spyrales

**Comment by strainel** [comment]
Merci @linogaliana
