### ISSUE TITLE
Ecrire un post sur RStudio Cloud

### ISSUE THREAD

**Issue by RLesur** [spyrales/web#13]
Je pense que vu le contexte, le service RStudio Cloud présente beaucoup d'avantages, notamment sur la collaboration.  
Pour tout dire, j'aimerais recommander ce service à des débutants ou des personnes qui veulent apprendre ensemble.  
Ca pourrait même être très utile pour aider des personnes qui sont coincées sur un projet : si elles travaillent avec RStudio Cloud, on peut accéder à leur projet en 1 clic.

Jusqu'ici, je ne l'ai que très peu utilisé mais je pense que ça vaut la peine de creuser cela au plus vite. Je compte m'atteler très rapidement à ce sujet. Si quelqu'un veut bosser avec moi là-dessus, ce serait avec grand plaisir.

Sur ce sujet, https://twitter.com/grrrck/status/1240673397627072512

**Comment by RLesur** [comment]
On pourrait même aller plus loin et faire comme Garrick Aden-Buie : mettre à disposition un projet de base dans lequel on aura configuré R en français (c'est rien à faire), installé les principaux packages, etc. Comme ça les personnes pourraient commencer à bosser rapidement.

**Comment by MaryleneH** [comment]
De mon côté, j'ai prévu d'écrire quelque chose sur RStudio Cloud (utilisation parfaite lorsque l'on veut faire une formation). Je prévois que ce soit mon nouvel outil quand je donne des formations R. J'enverrai le petit résumé que je compte faire une fois qu'il sera écrit

**Comment by RLesur** [comment]
J'avais également commencé un début de billet sur le sujet.
@MaryleneH Je pousse mon brouillon d'ici ce soir et comme ça on bosse ensemble dessus ?

**Comment by MaryleneH** [comment]
C'est parfait pour moi!
