### ISSUE TITLE
Ecrire un post de présentation de la formation accessible sur r.slmc.fr

### ISSUE THREAD

**Issue by martinchevalier** [spyrales/web#17]
Bonjour à tous, 

Sur proposition de @RLesur , voici une proposition de post de présentation de la formation que j'ai conçue accessible à l'adresse : http://r.slmc.fr. Les remarques sont les bienvenues.

Une initiation à R en cinq demi-journées
=======

Ce post très court pour proposer à celles et ceux qui souhaiteraient profiter du contexte actuel (et de l'accès parfois limité en télé-travail aux ressources de nos organisations respectives) pour se former à R à partir des **supports d'une formation que j'ai conçue et donnée à l'Insee de 2016 à 2018**. L'ensemble est librement accessible à l'adresse : http://r.slmc.fr. 

Ce support, initialement utilisé pour des formations en présentiel de deux jours, a en fait été pensé pour **servir aussi en auto-formation** (et a déjà été utilisé ainsi par de nombreux collègues) : l'ensemble du contenu est séquencé en **parties relativement courtes** avec des **exercices corrigés au fur et à mesure**. En termes de public, il s'adresse à des **statisticien·ne·s raisonnablement à l'aise avec un autre logiciel statistique** (par exemple SAS) et s'appuie pour l'essentiel sur des **données Insee** (un peu datées maintenant) : code officiel géographique, recensement de la population, enquête Emploi en continu, etc.

Plus précisément, la formation est organisée en **trois modules** : 

- le [module 1](http://r.slmc.fr/module1.html) (une demi-journée) vise à faire un premier **tour rapide des fonctionnalités de R** : environnement de travail (RStudio), manipulations statistiques élémentaires, import de données (SAS en particulier). L'objectif de ce premier module est de voir qu'une fois la nouvelle interface maîtrisée, **on retrouve assez facilement des points de repères**.

- le [module 2](http://r.slmc.fr/module2.html) (deux demi-journées) constitue un **détour coûteux mais nécessaire** : il vise à vous familiariser avec les **objets fondamentaux de R**, notamment les vecteurs et les listes, qui sont **sous-jacent à la plupart des opérations sur des données** que vous serez amenées à mener au quotidien. 

    D'expérience, ce deuxième module est **assez difficile pour les stagiaires** dans la mesure où il est **dense et semble assez éloigné de l'application concrète sur des données** ; **accrochez-vous néanmoins**, car ce qui est vu dans ce module constitue les véritables **fondations** de tout votre travail avec R.
    
- le [module 3](http://r.slmc.fr/module3.html) (deux demi-journées) **capitalise sur les apprentissages du module 2** pour revenir aux données statistiques "classiques" (des tables), en introduisant le type `data.frame` et l'**ensemble des manipulations utiles au quotidien** : recodage de variables, tri, concaténation, fusion, opérations sur plusieurs variables, etc. (en gros, l'étape DATA de SAS).

    Ce module propose également un **panorama sur le calcul de statistiques descriptives** (non-pondérées et pondérées) à partir de données de l'enquête Emploi en continu, avec en conclusion une **application pratique (avec correction) sur l'enquête Pisa 2012**.
    

**À noter que les durées indiquées après chaque module sont totalement indicatives** : l'essentiel est d'**aller à son rythme, de ne pas lâcher et si possible de continuer à pratiquer après** (sur un nouveau projet par exemple). 

J'ai mis à jour la page d'accueil de la formation le 19/03 pour mieux détailler tout ce qui relève de la **préparation du poste de travail** (installation de R, de RStudio, téléchargement des données), afin de **faciliter le suivi de la formation hors sphère Insee**. 

<hr>

**Remarque pour les faux débutants et les inités** Cette formation est totalement conçue autour de base R : elle ne s'appuie en particulier pas sur le [*package* dplyr](https://dplyr.tidyverse.org/) ni plus généralement sur le [tidyverse](https://www.tidyverse.org/) en tant que tel (même si bien sûr je parle de `haven` pour importer les fichiers SAS). Je fais une présentation très rapide de dplyr (ainsi que de [data.table](https://cran.r-project.org/web/packages/data.table/index.html)) dans ma [formation perfectionnement](https://teaching.slmc.fr/perf/index.html). Des initiations à R construites autour de dplyr seront très certainement partagées par leurs auteurs dans le cadre de spyrales.

<hr>

Le **code source de cette formation est accessible sur [github](https://github.com/martinchevalier/r_init)** et est **librement réutilisable sous &copy; 2016-2020 Martin Chevalier [CC BY-NC-SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/fr)**

**Comment by RLesur** [comment]
Merci beaucoup @martinchevalier ! C'est tout simplement... parfait !

**Comment by Welsh44** [comment]
> 
> 
> Merci beaucoup @martinchevalier ! C'est tout simplement... parfait !

Plus qu'à le mettre en ligne.

**Comment by RLesur** [comment]
@martinchevalier Nous allons insérer des bio pour les auteurs de billet (cf. #21). Pourrais-tu nous en passer une, s'il-te-plait ?

**Comment by martinchevalier** [comment]
OK niveau style et longueur je me cale sur celle de Stéphane.

**Comment by strainel** [comment]
très bon choix :)

**Comment by martinchevalier** [comment]
Je vous propose ça (si une PR est beaucoup plus pratique pour vous vous me dites hein), en html cela fait en gros 750 caractères.

<hr>

Fonctionnaire de l'[Institut national de la statistique et des études économiques](https://www.insee.fr) (Insee), je suis spécialisé en méthodologie statistique : j'ai d'abord été expert sondage au sein du Département des méthodes statistiques et suis depuis septembre 2018 responsable de la méthodologie du Recensement de la population.

Dans le cadre de mes travaux, j'ai élaboré un *package* (voir [ici](https://cran.r-project.org/package=gustave) ou [là](http://jms-insee.fr/jms2018s13_3/)) visant à faciliter l'estimation de variance dans les enquêtes par sondage de l'Insee (comprendre : dont la méthodologie est souvent compliquée). J'ai par ailleurs conçu des formations [initiation](http://r.slmc.fr) et [perfectionnement](https://teaching.slmc.fr/perf) à R. Enfin, j'accompagne actuellement l'adoption de R au sein de l'Insee en animant des ateliers au sein de ma direction.

**Comment by RLesur** [comment]
closed by https://github.com/spyrales/web/commit/26f47713e9166e32b52d797f833847f1202d3168
