### ISSUE TITLE
ajouter la traduction de certains champs

### ISSUE THREAD

**Issue by strainel** [spyrales/web#27]
créer un répertoire i18n & paramétrer un fichier `fr.yaml`

**Comment by RLesur** [comment]
Il y a aussi des termes anglais écrits en durs dans les partials. Un peu plus casse-pied.

**Comment by strainel** [comment]
ha oui ? où par exemple.

**Comment by RLesur** [comment]
Ici par exemple https://github.com/themefisher/airspace-hugo/blob/abf0e9c14f174294fe07f745694b8427c1457cfc/layouts/_default/list.html#L92
