### ISSUE TITLE
augmenter le temps d'attente dans le slider

### ISSUE THREAD

**Issue by strainel** [spyrales/web#29]
voir si possible de modifier le paramètre du slider dans le js/script

**Comment by LVerneyPEReN** [comment]
à modifier dans le thème directement (airspace-hugo) : https://github.com/themefisher/airspace-hugo/blob/aed3250fa7db6b56fa65be73ed1e3ea52f658e59/assets/js/script.js#L26-L47

Pas sûr que ce soit acceptable. Sinon, quick and dirty, je dois pouvoir faire un patch à base de search and replace (`sed`) dans `_deploy.sh` pour aller modifier directement dans le `js/script.min.js` produit.

**Comment by strainel** [comment]
une idée qui me séduit... 
je pensais aussi à créer un paramètre. 

partons pour le quick-and-dirty et nous verrons ensuite... tu le fais @LucasVerneyDGE  ?

**Comment by RLesur** [comment]
tant qu'à faire du quick and dirty, faisons un peu moins dirty : il suffit de déplacer le script dans `assets/js` (à créer). Hugo ira chercher celui là.

**Comment by strainel** [comment]
j'ai tout de même posé la question
https://github.com/themefisher/airspace-hugo/issues/72

@RLesur : s'il modifie leur `script.js`, le nombre ne sera plus à jour... non ?

**Comment by RLesur** [comment]
@strainel effectivement, le gros avantage d'Hugo, c'est qu'on peut facilement customiser un thème en déplaçant un de ses fichiers et en le modifiant (comme dans #32 ). L'inconvénient, c'est la maintenance de ces versions modifiées quand on met à jour le thème. C'est un arbitrage.

**Comment by LVerneyPEReN** [comment]
En effet, très pratique cette possibilité ! J'ai fait une PR type en doublant le temps de slick : https://github.com/spyrales/web/pull/34.

Je mettrai à jour suivant les retours airspace / la maintenance voulue.
