### ISSUE TITLE
Problèmes de navigation

### ISSUE THREAD

**Issue by RLesur** [spyrales/web#39]
Plusieurs internautes (dont moi) rencontrent des problèmes de navigation.  
Les pages sont parfois blanches (difficile à reproduire) sur desktop, mobile, avec FF ou Chrome/Chromium.  

En revanche, je n'ai pas rencontré ce problème jusqu'ici en local lorsque je builde le site avec Hugo.

**Comment by strainel** [comment]
Je pense à un problème de cache. Un reload forcé (shift+reload sur macOS) affiche la page.

**Comment by RLesur** [comment]
@strainel Bien vu, ça résoud les problèmes sur mon PC également. Tiens, je réalise que je ne sais pas comment faire ça sur mobile.

**Comment by RLesur** [comment]
Est-ce que vous pensez qu'en rajoutant `<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">` dans `layouts/partials/head.html` (à créer), ça résoudrait le problème ?

**Comment by RLesur** [comment]
FTR, Netlify est désormais utilisé (voir https://github.com/spyrales/web/commit/22b4afc920b9cd6cfb1f710578bd91a285a563e7 et https://github.com/spyrales/web/commit/24d006f5fd6570b72dfe17dbcbeeff1e85900ac8)

A toutes et à tous, merci de reporter vos expériences de navigation du site <https://spyrales.netlify.com/>.
