### ISSUE TITLE
Ecrire un article en Français sur "comment rédiger un reprex"

### ISSUE THREAD

**Issue by MaryleneH** [spyrales/web#40]
Bonjour à tous, 
Lorsque l'on débute et que l'on a besoin d'aide, il est utile de solliciter la communauté de la meilleure manière qu'il soit pour obtenir rapidement de l'aide sur le problème que l'on rencontre. Il faudrait sans doute rédiger un article décrivant les éléments que doit contenir l'exemple quand on sollicite de l'aide. Qu'en   ##pensez-vous?

**Comment by Welsh44** [comment]
Très bonne idée @MaryleneH 
Une idée à partir de ce qui se fait sur grrrr ?
Tu as déjà un brouillon ?

**Comment by MaryleneH** [comment]
Oui je pense qu'il faut partir de ce qui se fait sur Grrr c'est le plus simple. Je n'ai pas encore de brouillon mais je peux m'en occuper ce week-end.

**Comment by MaryleneH** [comment]
Entre temps, ThinkR a rédigé un excellent article sur le sujet 👍 
https://thinkr.fr/reprex-ou-comment-demander-de-laide-efficacement/

Peut-être faire un lien sur spyrales menant à cet article suffirait ? 😃 🥰
