### ISSUE TITLE
Proposer une présentation de Git et quelques commandes

### ISSUE THREAD

**Issue by Welsh44** [spyrales/web#41]
Je me suis dit que tout le monde n'était pas nécessairement familier...
Je propose un version beta.

**Comment by Welsh44** [comment]
# Mémo Git

L'idée de cet article est de fournir d'une part quelques éléments de compréhension sur Github et Git, mais aussi de fournir quelques commandes de base pour démarrer.

## C'est quoi ma dernière version déjà ?
En vous (auto-)formant à R et/ou Python, en parcourant les articles de [spyrales](http://spyrales/github.io/web/), vous croiserez également des compagnons nommés Github ou Git. Mais qu'ont-ils à voir avec R ou Python ?

Assez vite dans votre apprentissage de R ou de Python, vous allez devoir revenir en arrière parce que finalement ce n'était pas la bonne direction dans votre code. Ou bien vous allez vouloir partager avec quelqu'un. Rapidement vous aurez envie de travailler à plusieurs...

C'est là qu'intervient le **Contrôle de version**. Derrière ces termes se cache des mécanismes permettant de garder trace des modifications, de pouvoir bifurquer, de pouvoir revenir en arrière... Si vous travaillez à plusieurs sur un projet, cela permet à un des acteurs de travailler sur sa partie, de la tester en toute sérénité, de la faire, défaire, refaire autant que de besoin. Et une fois que sa partie fonctionne correctement, il peut la fusionner avec le reste.

## Git
**Git** est un système de contrôle de version, open-source, mis au point par *Linus Torvalds* en 2005. Linus Torvalds ?... Mais si ! le créateur de Linux ! Tout comme Linux, il l'a développé pour ses besoins personnels car il n'aimait pas les produits existants. Car oui ! le contrôle de version existait avant Git....

La particularité de Git est de mettre en oeuvre un système de contrôle de version distribué. Donc tous les acteurs d'un projet ont l'intégralité de la base du code et de son historique, ce qui facilite grandement les opérations de fusion. Mais arrêtons là ces propos techniques qui peuvent sembler ésotériques à certains d'entre vous.

## Github
[Github](https://github.com) est une société qui offre un service d'hébergement de référentiels Git dans les nuages (dans le *cloud*). Son avantage est tiré de son interface relativement intuitive et conviviale. Tellement que certains s'en servent pour écrire des livres ! Et surtout n'importe qui peut héberger un dépôt sur Github d'où sa popularité.

Aujourd'hui, vous trouverez beaucoup de projets dont la distribution se fait à travers un dépôt Github. Et pour l'installation, c'est 
> Vous n'avez qu'à cloner le dépôt !
Alors je vais essayer de fournir quelques commandes de base pour démarrer.

## Les principales commandes

### Cloner un dépôt
Au vu de ce qui précède, commençons par cloner un dépôt existant. Il faut connaîte d'abord le lien permettant d'accès au dépôt. Le projet est hébergé dans le référentiel d'un utilisateur de Github. Le lien est donc de la forme `https://github.com/<uilisateur>/<pojet>`. Ainsi le projet reveal.js est hébergé sur le référentiel de l'utilisateur hakimel.

La commande à passer est donc
```
git clone https://github.com/hakimel/reveal.js.git
```
ce qui créera un répertoire nommé `reveal.js` dans le répertoire où vous lancez la commande.


### Historiser ses modifications
Une fois le projet cloné, vous pouvez librement modifier **sur votre environnement** le projet. Bien sûr, vous pouvez profiter **localement** d'historiser vos modifications...puisque Git est un système distribué.
La commande pour historiser vos modifications est `git commit`. Encoe faut-il savoir ce qu'on historise...

Deux cas de figure : soit vous modifiez un fichier issu du projet, soit vous souhaitez historiser un fichier que vous avez ajouté. Dans le premier cas, la commande `git commit`suffit.

Dans le second cas, il faut indiquer que vous souhaitez **ajouter** le fichier à l'historisation. Dans ce cas, la commande est
```
git add <nom du fichier>
```
Désormais on peut sauvegarder les modifications. Et pour ne pas oublier pourquoi on l'historise à ce moment là, on peut ajouter un message :
```
git commit -m 'Mon message pour expliquer'
```

**Comment by Welsh44** [comment]
Ici : https://github.com/Welsh44/web/blob/master/content/french/blog/20200327_PresentationGit

pas encore très doué sur les PR...

**Comment by RLesur** [comment]
J'aime bien l'idée d'un billet introductif à git.

@Welsh44 tu veux qu'on fasse comment ? on peut copier-coller sauvagement ton post dans une branche et bosser à plusieurs dessus ou bien si tu es intéressé, voir ensemble le flow pour les PR, @strainel l'a décrit ici : https://github.com/spyrales/web/blob/master/comment-faire-une-pr.md  
J'ai jeté un rapide coup d'oeil à ton fork. Il y a des commits sur la branche master ce qui, dans l'optique d'une contribution régulière, est réellement gênant (c'est plus toi qui sera gêné que les mainteneurs de `spyrales/web`).

Dis-moi comment tu veux que l'on procède.

**Comment by Welsh44** [comment]
@RLesur le copier-coller ne me gêne pas et peut amener plus de choses sur le contenu. J'utilsie Git (très) simplement.
Je ,propose un copîer-coller "bourrin" et pour le prochain je fais le mode propre.

**Comment by Welsh44** [comment]
@RLesur en fait je suis en train de faire la branche. J'arrive ! Pas trop tard ? Tu as déjà commecné ?

**Comment by Welsh44** [comment]
@RLesur de fausse manip en fausse manip...
On oublie tout, je forke, clone, branche et fais une PR.
A moins que tu n'aies commencé ?

**Comment by RLesur** [comment]
non, je ne suis pas du tout là dessus :wink: 
je te laisse forker, cloner, brancher en paix

**Comment by Welsh44** [comment]
La PR #48 est faite
