### ISSUE TITLE
Rendre compatible spyrales/web avec blogdown

### ISSUE THREAD

**Issue by RLesur** [spyrales/web#42]
Le package R [**blogdown**](https://bookdown.org/yihui/blogdown/) offre de très nombreuses fonctions _helpers_ permettant de faciliter l'utilisation de Hugo pour les utilisateurs de R.  
C'est d'ailleurs la raison pour laquelle Hugo est devenu très populaire dans l'écosystème R.

Un exemple de fonction _helper_ très pratique est la fonction `blogdown::install_hugo()`. L'intégralité de la procédure d'installation de Hugo décrite dans la partie [Installation de Hugo extended 0.67.0](https://github.com/spyrales/web#installation-de-hugo-extended-0670) se résume pour les utilisateurs de **blogdown** à la ligne suivante : 

```r
blogdown::install_hugo("0.67.0")
```

La fonction `blogdown::install_hugo()` fonctionne bien évidemment sous tous les systèmes.  

Les différentes opérations courantes (création d'un post, génération du site web en local...) sont également facilitées par l'existence de fonctions idoines.  
Les utilisateurs de RStudio disposent également d'[add-ins](https://bookdown.org/yihui/blogdown/rstudio-ide.html) leur permettant d'accéder à l'ensemble de des fonctions courantes en 1 clic. Voici une copie d'écran des add-ins disponibles dans RStudio : 

![blogdown_addins](https://user-images.githubusercontent.com/19177171/77796928-7e8c6680-7070-11ea-8022-156fd605307c.png)

Je me disais que cela pourrait peut-être faciliter les contributions à `spyrales/web`. En effet, les utilisateurs de RStudio n'auraient notamment aucune commande à passer pour créer un nouveau billet, vérifier le site localement, etc.  

Les changements à opérer dans le repository `spyrales/web` me semblent relativement mineurs pour parvenir à offrir cette simplicité d'usage. En supposant qu'on souhaite rendre `spyrales/web` compatible avec **blogdown** et RStudio, il faudrait : 

- créer un fichier `Rproj` qui un fichier de paramètres pour les projets RStudio
- modifier le `.gitignore` pour rajouter les fichiers internes à l'IDE RStudio

Qu'en pensez-vous ?

**Comment by MaryleneH** [comment]
Je trouve que c'est une bonne idée qui pourra impulser la rédaction de billets.
