### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by RLesur** [spyrales/web#44]
On n'a du tout évoqué la question de la licence jusqu'ici.  
En l'absence de licence, il n'y a pas de droit de réutilisation.

Veut-on utiliser une licence ouverte pour le contenu de ce site ?  

Si oui, il faudrait en choisir une et bien évidemment, demander l'accord de tous les auteurs.

**Comment by strainel** [comment]
Du même avis : ok pour moi pour une licence ouverte.
La licence ouverte v2 d'Etalab s'impose me semble-t-il.

**Comment by strainel** [comment]
On peut éventuellement commencer par relister les auteurs et leur demander la mise en licence ouverte de l’article rédigé ?

**Comment by strainel** [comment]
Ok je m’en occupe ce week-end @RLesur

**Comment by strainel** [comment]
Bonjour @MaryleneH @RLesur @jmbernabotto @Welsh44 @MaelTheuliere @martinchevalier @larmarange @juba 

Vous avez publié un article dans le blog de spyrales. Or nous n'avons pas fixé de doctrine sur la licence de ces articles. Nous proposons de les mettre en licence ouverte (licence Etalab).

Êtes vous opposés ou non à une mise en licence ouverte de votre article blog (pas le contenu de vos contributions hors du site évidemment) ?

Votre réponse est attendue ici en commentaire ! 

@MaryleneH  : OK
@RLesur : OK
@jmbernabotto : OK
@Welsh44 : OK
@MaelTheuliere : OK
@martinchevalier : OK
@larmarange : OK
@juba : OK

**Comment by MaelTheuliere** [comment]
Hello 
Moi c'est bon pour être en lol !

**Comment by juba** [comment]
Aucun souci bien sûr. On a bien besoin de lol en ce moment en plus.

**Comment by larmarange** [comment]
Aucun souci pour une licence ouverte

JL

Le ven. 10 avr. 2020 à 15:51, Julien Barnier <notifications@github.com> a
écrit :

**Comment by jmbernabotto** [comment]
Ça me va très bien !

**Comment by strainel** [comment]
@MaryleneH
@RLesur 
@Welsh44 
@martinchevalier

êtes-vous d'accord sur la mise en licence ouverte de vos articles du blog de spyrales (et non de vos articles hors spyrales dont vous avez pu faire la "promotion" ?

merci !!

**Comment by MaryleneH** [comment]
Oui aucun problème. 
J’ai oublié de répondre plus tôt mais bien sûr sans soucis :-)

Marylene

**Comment by Welsh44** [comment]
Désolé de ne pas avoir vu la notification avant @strainel 
Pas de souci

**Comment by RLesur** [comment]
Exact, j'avais soumis l'idée mais ça ne valait pas accord explicite ! c'est un grand oui !

**Comment by martinchevalier** [comment]
Oui, aucun problème pour passer mon billet en licence ouverte !

**Comment by strainel** [comment]
top merci à tous !
