### ISSUE TITLE
Un article sur datatable pour les utilisateurs R

### ISSUE THREAD

**Issue by linogaliana** [spyrales/web#63]
Je viens de publier une introduction à `data.table` sur mon [blog perso](https://linogaliana.netlify.com/post/datatable/datatable-intro/). Ca fait suite au travail avec Olivier Meslin sur la doc `utilitR` (nouveau *branding* !). :smile:

Ca rentre dans le champ de `spyrales` donc si vous pensez que c'est intéressant, je peux aussi le *pusher* sur ce blog. C'est un peu long car c'est une introduction assez complète sur le sujet

**Comment by strainel** [comment]
@linogaliana c'est vraiment top comme article, pas encore tout lu, mais très intéressant pour qui veut l'utiliser. Je ne pense pas qu'il faille le pusher en direct sur le blog, mais un article de quelques paragraphes permettrait de le présenter et de faire une référence vers ton blog. 
qu'en penses tu ?

**Comment by linogaliana** [comment]
Merci @strainel ! Ok ça me va également comme principe :smile: c'est vrai que c'est une introduction approfondie !

**Comment by RLesur** [comment]
Même avis ! je trouve ça vraiment bien.  
J'aurais bien mis une petite phrase de contexte sur le mode "traiter des données volumineuses sans base de données" ou "vous avez des données volumineuses et n'avez pas d'infrastructure de type Spark"... vous voyez ce que je veux dire.

**Comment by linogaliana** [comment]
>  "traiter des données volumineuses sans base de données" ou "vous avez des données volumineuses et n'avez pas d'infrastructure de type Spark"

:100: % d'accord, je modifie dans la journée ! et je vous fait une proposition d'intro dès que possible
