### ISSUE TITLE
Rédiger un article sur DDODS

### ISSUE THREAD

**Issue by strainel** [spyrales/web#64]

**Comment by Welsh44** [comment]
Pour Juliette ? (@JulietteS)

**Comment by JulietteS** [comment]
Pas dispo d'ici la mise en service : voir avec @fcomte ou @insee-unissi

**Comment by Welsh44** [comment]
Est-ce que ce n'est pas fait avec [cet article](https://spyrales.netlify.app/blog/20200408-premierspas-onyxia/)

**Comment by strainel** [comment]
oui disons que c'est fait ! on pourra toujours réouvrir.
