### ISSUE TITLE
Rédiger un article sur les avantages de Pycharm community edition comme IDE

### ISSUE THREAD

**Issue by raphaeleadjerad** [spyrales/web#74]
Je voudrais bien proposer un article sur les avantages de **Pycharm Community Edition** pour écrire du Python:
- l'**analyse de script en direct** pour mettre en avant de nombreux types d'erreurs/warnings (mise en forme PEP 8, erreurs potentielles, appel de modules finalement non utilisés dans le code, modules non installés, etc.,) ce qui permet de contrôler la propreté de son code très rapidement et efficacement
- l'**interface avec Git** qui est vraiment très bien : le *Local Changes* avec les fichiers versionnés et leurs modifications depuis le dernier commit,  qui permet d'avoir un *side by side viewer* des changements (très modulable), le *log* qui permet de suivre visuellement la branche sur laquelle on se trouve par rapport au master et à l'ensemble des branches du projet, etc. tout en pouvant utiliser les commandes Git soit en ligne de commande via le terminal intégré soit via l'interface de Pycharm 
- la gestion des  **environnements virtuels** conda, virtualenv, etc. dans Pycharm 

Ce serait une petite mise en valeur de ces différents aspects avec des captures d'écran et quelques cas pratiques par exemple.  
Je ne sais pas si cela pourrait vous intéresser pour Spyrales ?

**Comment by RLesur** [comment]
Merci beaucoup pour la proposition ! A titre personnel, cela m'intéresse beaucoup : le peu de python que je fais est dans VSCode, mais ce n'est jamais pour des sujets de data science.  
Et vu que je n'arrive vraiment pas à me faire à Jupyter, je trouverais bien d'avoir une petite présentation de Pycharm.
