### ISSUE TITLE
ajouter deux retours "pourquoi je contribue à la communauté" sur la page d'accueil (zone trophées)

### ISSUE THREAD

**Issue by strainel** [spyrales/web#8]
il y a un carrousel qui peut accueillir des retours ou des motivations à participer.
cela donne de la place à l'humain... avec une photo c'est mieux. :)

**Comment by Welsh44** [comment]
Exact. Mais dans la mesure où c'est le démarrage, le retour utilisateur est un peu fort. Ce pourrait être 2-3 qui indiquent ce qui les motive dans cette démarche. A piquer dans le présentations sur tchap ?

**Comment by strainel** [comment]
ce qui motive notre participation, c'est déjà beaucoup je crois. je vais poster sur tchap.

**Comment by RLesur** [comment]
FTR, @antuki et @MaryleneH se sont proposées

**Comment by MaryleneH** [comment]
Pourquoi je contribue à la communauté " Quand j'ai décidé de passer de SAS à R, j'ai pu trouver une communauté de passionnés de R active, bienveillante et toujours prête à m'aider. Contribuer à des démarches telles que Spyrales devient maintenant un réflexe. Que l'on soit débutant ou plus expérimenté, l'entraide est indispensable et c'est ce qui rend le travail si agréable". Pour la photo, il suffit de reprendre celle de mon GitHub.

**Comment by antuki** [comment]
A mon tour (avatar github également) « J'adore explorer la polyvalence de ces logiciels : le fait de pouvoir faire des cartes, graphiques et même des applis webs avec un même langage permet aux différents métiers de se rencontrer et de communiquer, et à une même personne d'apprendre, avec plaisir et curiosité, plusieurs métiers ! » 

PS : la dernière fois que j'avais regardé je trouvais que le caroussel bougeait un peu vite et que l'on n'avait pas le temps de lire le message en entier avant que ça passe à un autre témoignage.

Edit : et j'ai vu qu'il fallait mettre un "titre" sous le témoignage. Pour favoriser la diversité des profils vous pouvez mettre quelque chose qui ressemble à "Agent de l'Insee en formation complémentaire à l'ENSAE"

**Comment by strainel** [comment]
merci ; je mets à jour ce jeudi

**Comment by strainel** [comment]
merci à vous  ; c'est publié.
@antuki @MaryleneH : si besoin de modifier quelque chose, n'hésitez pas.
