### ISSUE TITLE
Rédiger un article "Comment publier une formation sur Onyxia"

### ISSUE THREAD

**Issue by RLesur** [spyrales/web#82]
Suite à la publication du premier tutoriel de @jmbernabotto dans [la rubrique "Formations"](https://spyrales.sspcloud.fr/trainings) d'Onyxia, je me dis que ce serait pas mal de faire un billet expliquant la marche à suivre.  

Pour l'instant, on ne la fait que pour un notebook jupyter. Je vois assez bien comment le faire pour un projet RStudio.

Ca permettrait de présenter au passage diverses fonctionnalités d'Onyxia dont on n'a pas encore parlé.

Je vais commencer à l'écrire.  
@fcomte, je te le soumettrai, si tu veux bien me relire.

**Comment by fcomte** [comment]
avec plaisir :)
