### ISSUE TITLE
Corriger l'article sur VISION

### ISSUE THREAD

**Issue by strainel** [spyrales/web#89]
@jmbernabotto 
Suite à une trop rapide validation de ma part, le projet d'article n'était pas corrigé. 
J'ai donc mis l'article en mode brouillon et il reste à corriger.

**Comment by strainel** [comment]
oui stp : tu corriges et tu fais une PR.

**Comment by jmbernabotto** [comment]
j'ai corrigé et recréé une nouvelle branche. L'ancienne est donc devenu obsolète. Je l'ai détruite.

**Comment by strainel** [comment]
c'est tout bon ; j'ai corrigé en direct une dernière faute de frappe & j'ai enlevé le mode brouillon.
